### ISSUE TITLE
got problem on meteoserver

### ISSUE THREAD

**Issue by chinjenlin** [jonas-hagen/meteo-logger-server#3]
I found your WXT log solution is very useful, thanks for your contributions!

I got problem on meteoserver. I try to let you know what problem I occurred, so I type “ ~/meteo-logger-server-master/meteo $ sudo python3 server.py” and I got error message in the attached.  I will be appreciated if you could advise me how to proceed. 

Thank you!
Chin-Jen
[error.txt](https://github.com/jonas-hagen/meteo-logger-server/files/7326887/error.txt)

**Comment by chinjenlin** [comment]
I found the problem coming from the dependency for numpy. Now solved. Thank you!

**Comment by jonas-hagen** [comment]
Ok, good to hear!
